-- Auto-generated SQL to fix fact_shipments detection
-- Generated by tools/generate_fix_sql.py
-- Run this in Supabase SQL Editor

UPDATE fact_shipments 
SET detected_family = 'Black Fox', 
    detected_format = 'BIB 20L', 
    detected_category = 'bib20'
WHERE source_description = 'Dunkertons BLACK FOX ORGANIC Cider BIB';

UPDATE fact_shipments 
SET detected_family = 'Black Fox', 
    detected_format = 'Keg 30L', 
    detected_category = 'keg30'
WHERE source_description = 'Dunkertons BLACK FOX Cider 50L Keg 6%';

UPDATE fact_shipments 
SET detected_family = 'Craft', 
    detected_format = 'Keg 30L', 
    detected_category = 'keg30'
WHERE source_description = 'Dunkertons CRAFT Cider 50L ** Keg ** 5%';

UPDATE fact_shipments 
SET detected_family = 'Black Fox', 
    detected_format = 'None', 
    detected_category = 'unknown'
WHERE source_description = 'Dunkertons BLACK FOX CIDER Bottles 7%';

UPDATE fact_shipments 
SET detected_family = 'Craft', 
    detected_format = 'Can 330ml', 
    detected_category = 'can330'
WHERE source_description = 'Dunkertons CRAFT Cider 5% Cans';

UPDATE fact_shipments 
SET detected_family = 'Craft', 
    detected_format = 'None', 
    detected_category = 'unknown'
WHERE source_description = 'Dunkertons CRAFT Cider 5% Bottles';

UPDATE fact_shipments 
SET detected_family = 'Craft', 
    detected_format = 'None', 
    detected_category = 'unknown'
WHERE source_description = 'Dunkertons CRAFT Cider 5% Bottlesx8';

UPDATE fact_shipments 
SET detected_family = 'Craft', 
    detected_format = 'None', 
    detected_category = 'unknown'
WHERE source_description = 'Dunkertons CRAFT Cider 5% Bottles 11pack';

UPDATE fact_shipments 
SET detected_family = 'Premium', 
    detected_format = 'None', 
    detected_category = 'unknown'
WHERE source_description = 'Dunkertons PREMIUM Cider Bottles';

UPDATE fact_shipments 
SET detected_family = 'Perry', 
    detected_format = 'None', 
    detected_category = 'unknown'
WHERE source_description = 'Dunkertons PERRY Cider Bottles';

UPDATE fact_shipments 
SET detected_family = 'Vintage', 
    detected_format = 'None', 
    detected_category = 'unknown'
WHERE source_description = 'Dunkertons VINTAGE CIDER Bottles';

UPDATE fact_shipments 
SET detected_family = 'Dry', 
    detected_format = 'BIB 20L', 
    detected_category = 'bib20',
    internal_product_code = 'FPDRY'
WHERE source_description = 'Dunkertons DRY ORGANIC Cider BIB';

UPDATE fact_shipments 
SET detected_family = 'Dabinett', 
    detected_format = 'None', 
    detected_category = 'unknown'
WHERE source_description = 'Dunkertons DABINETT CIDER Bottles';

UPDATE fact_shipments 
SET detected_family = 'Mulled', 
    detected_format = 'BIB 10L', 
    detected_category = 'bib10',
    internal_product_code = 'FPMULLED'
WHERE source_description = 'Dunkertons 10L Mulled Cider **BIB**';

