#!/usr/bin/env python3
"""
Generate SQL to fix detected_family, detected_format, and internal_product_code
for all existing fact_shipments records based on current detection logic.
"""
import sys
import json
from detection import detect_all

# Mapping of (brand_family, pack_format) -> internal_product_code
# Based on dim_product_internal
PRODUCT_CODE_MAP = {
    ("Mulled", "BIB 10L"): "FPMULLED",
    ("Mulled", "BIB 20L"): "FPMULLED",
    ("Dabinett", "Bottle 500ml"): "FPDABINETT",
    ("Dabinett", "Bottle 660ml"): "FPDABINETT",
    ("Dry", "BIB 20L"): "FPDRY",
    ("Dry", "Bottle 500ml"): "FPDRY",
    ("Dry", "Bottle 660ml"): "FPDRY",
    # Add more mappings as needed
}

def main():
    # Read JSON from stdin
    data = json.load(sys.stdin)
    
    print("-- Auto-generated SQL to fix fact_shipments detection")
    print("-- Generated by tools/generate_fix_sql.py")
    print("-- Run this in Supabase SQL Editor\n")
    
    for row in data:
        desc = row.get('source_description', '')
        if not desc:
            continue
            
        # Run detection
        attrs = detect_all(desc, duoi=None)
        family = attrs['detected_family']
        format_val = attrs['detected_format']
        category = attrs['detected_category']
        
        # Determine internal_product_code
        product_code = PRODUCT_CODE_MAP.get((family, format_val))
        
        # Generate UPDATE statement
        # Escape single quotes in description
        safe_desc = desc.replace("'", "''")
        
        if product_code:
            sql = f"""UPDATE fact_shipments 
SET detected_family = '{family}', 
    detected_format = '{format_val}', 
    detected_category = '{category}',
    internal_product_code = '{product_code}'
WHERE source_description = '{safe_desc}';
"""
        else:
            sql = f"""UPDATE fact_shipments 
SET detected_family = '{family}', 
    detected_format = '{format_val}', 
    detected_category = '{category}'
WHERE source_description = '{safe_desc}';
"""
        
        print(sql)

if __name__ == '__main__':
    main()
